### ISSUE TITLE
Provide type hints to pyodbc/unixodbc/db driver for parameters in SQL statements

### ISSUE THREAD

**Issue by BY-jk** [blue-yonder/sqlalchemy_exasol#13]
SQLAlchemy does not call the 'setinputsizes' function prior executing statements. This is usually not an issue can cause unwanted effects when a lot of parameters are transmitted. EXASOL reserves up to 2.000.000 bytes per parameter if no type information is provided by the caller. This causes statements with more than 266 to fail.
Current workaround is to avoid prepared statements when an SQL statement has more than x parameters. The sane solution is to use the type information available in SQLAlchemy to call setinputsizes prior execution (pre_exec method). This is only done in the Oracle dialect:

https://github.com/zzzeek/sqlalchemy/blob/be3c185fd48c2abcc5d9f54dd0c415e15c33184f/lib/sqlalchemy/dialects/oracle/cx_oracle.py#L462

TODO: 
- Have a test case that fails
- Implement something similar to Oracle in the pre_exec method of the EXA dialect.

**Comment by StephanErb** [comment]
This seems to be addressed by https://github.com/blue-yonder/turbodbc.

See: https://github.com/blue-yonder/turbodbc/blob/master/python/turbodbc/cursor.py#L84-L96

**Comment by MathMagique** [comment]
pyodbc's strategy for handling large string parameters (as indicated by the database) is to ignore the maximum string size given by the database and start with a small one instead. Exponential growth is applied when actual parameter sizes exceed the buffer size.

**Comment by StephanErb** [comment]
You mean turbodbc's strategy?

**Comment by jank** [comment]
Closed due to inactivity.
