### ISSUE TITLE
Support for DISTRIBUTE BY

### ISSUE THREAD

**Issue by BY-jk** [blue-yonder/sqlalchemy_exasol#20]
Support DISTRIBUTE BY for tables to control distribution of table records within the cluster.

**Comment by fmarczin** [comment]
+1

**Comment by BY-jk** [comment]
The implementation of the mysql dialect might give some hints on how to achieve this:
https://github.com/zzzeek/sqlalchemy/blob/c3d898e8d06c7e549bb273fc8654f5d24fab2204/lib/sqlalchemy/dialects/mysql/base.py#L1887

**Comment by BY-jk** [comment]
DISTRIBUTE BY  (D_B) according to EXASOL spec allowed in:

    ALTER TABLE <name> DISTRIBUTE BY col 
    CREATE TABLE <name> ( col_specs, DISTRIBUTE BY a,b )

Implementation is ready when:

* D_B spec can be added via create table or alter table
* D_B spec is correctly reflected into table meta data when inspecting tables via SQLA

**Comment by BY-jk** [comment]
Implementation idea:

* define a class DistributeByConstraint (like ForeignKeyConstraint)
* implement rendering
* implement reflection (similar to autoincrement)
* add test cases

**Comment by BY-jk** [comment]
The branch distribute_by contains a basic version that renders DISTRIBUTE BY as table constraint. As part of that implementation, the generation of FOREIGN KEY was redone as it was a bit awkward (copy & paste of super class implementation of create_table_contraints).

Missing is:
- Support ALTER TABLE for DistributeByConstraints via AddConstraint and DropConstraint. Requires test case and implementation.

**Comment by BY-jk** [comment]
I had another look at making Table reflection recreate DistributeByConstraints. The way to go seems to be via dialect specific table options (as done for the mysql Dialect). However, this looks like wading through quite some SQLA framework code. I am not signing up for this right now. @fmarczin: are you willing to explore? 
Otherwise, if the ALTER TABLE stuff is implemented we could merge into master.

**Comment by BY-jk** [comment]
all done

**Comment by fmarczin** [comment]
@BY-jk You're fast!! :open_mouth: 
Awesome!!

**Comment by BY-jk** [comment]
Released with 0.9.1
