### ISSUE TITLE
Required [EXAODBC] section in odbcinst.ini

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/sqlalchemy_exasol#30]
It seems that sqlalchemy_exasol assumes an [EXAODBC] section in the odbcinst.ini and does not interpret the DRIVER=value from odbc.ini like pyodbc does when a DSN is specified. Could this be changed?

**Comment by BY-jk** [comment]
Seems reasonable, will need to have a look into this.

**Comment by fmarczin** [comment]
I ran into this, too. I think the source of the problem is that for DSN-less connections, the driver name is put into curly braces (pyodbc.py:78). This makes it impossible to directly provide a driver file.

**Comment by BY-jk** [comment]
Ok I checked this. @FlorianWilhelm, I am not sure if you try to connect via a connection URL (exa+pyodbc://...) or via a DSN.

Connecting via a DSN you can pass the relevant section of the driver ini file as parameter. EXAODBC is just the default. E.g. using the following connecting string

    exa+pyodbc://<user>:<pwd>@<ip-range>:<port>/schema?driver=MYDRIVER

would look for the section 'MYDRIVER' in your odbcinst.ini.

This works for me.

**Comment by FlorianWilhelm** [comment]
@BY-jk I connected with DSN only, so no connection URL. The problem is that if you provide the DRIVER= parameter **inside** your DSN section, it still checks for [EXAODBC].

**Comment by BY-jk** [comment]
Works for me. I removed all entries from the odbcinst.ini (the ini file holding the global driver directive). I added a section like this to my odbc.ini (the file holding system DSNs):

    [EXA_TEST]
    DRIVER=/path/to/libexaodbc-uo2214lv1.so
    EXAHOST=<ip range>:<port>
    EXASCHEMA=some_schema

and than connected with

    from sqlalchemy import create_engine
    e = create_engine('exa+pyodbc://USER:PWD@EXA_TEST')
    c = e.connect()
    r = c.execute('select 42 from dual;')

And I got the answer I was looking for

**Comment by JivanRoquet** [comment]
@BY-jk this solution leads to the following error:

```
InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [unixODBC][Driver Manager]
Data source name not found, and no default driver specified (0) (SQLDriverConnect)')
```

**Comment by jank** [comment]
Can you please share more details on your setup, e.g.:

- Operating system
- (unix?)ODBC version
- Python version
- SQLAlchemy_exasol version
- your odbc configuration

The error message suggests that you do not have the data source `EXA_TEST` defined (assuming you copied and pasted the connection string from the snippet above.

If this is your connection string: 'exa+pyodbc://USER:PWD@EXA_TEST'

you are using the EXASOL dialect (indicated by 'exa'), connecting using pyodbc (indicated by 'pyodbc'), with USER and PWD as username and password, using the ODBC data source 'EXA_TEST'.

Maybe the data source is not defined in your
