### ISSUE TITLE
Reflection supports no doc and default attributes for columns

### ISSUE THREAD

**Issue by FlorianWilhelm** [blue-yonder/sqlalchemy_exasol#41]
I used following code to reflect a table:

> table = sqla.Table('M_PREDICTIONS', sqla.MetaData(), autoload=True, autoload_with=engine, schema=mining_schema)

Iterating over the columns of table revealed that the `doc` attribute is always empty and I think this should correspond to the `Comment` in Exasol. Also the `default` attribute  for the column is always empty. This looks like the reflection is not fully implemented.

**Comment by BY-jk** [comment]
You are right, the reflection part is most likely buggy. _get_all_columns https://github.com/blue-yonder/sqlalchemy_exasol/blob/master/sqlalchemy_exasol/base.py#L561 seems to be the place to check. Do you consider writing a PR?

**Comment by jank** [comment]
default is reflected by now. doc will not be supported for now.
