### ISSUE TITLE
Dialect does not autocommit for TRUNCATE Table Statement

### ISSUE THREAD

**Issue by hoffmann** [blue-yonder/sqlalchemy_exasol#53]
The Exasolution database supports the TRUNCATE Table Statement, but this data changing operation is not properly handled (i.e. no commit is executed) when executed with `autocommit=True` (default  in create_engine).  

``` python
from sqlalchemy import *
dsn = "exa+pyodbc://sys:exasol@localhost/"
db = create_engine(dsn)

con = db.connect()
con.execute("create table test.test(id integer, val varchar(50))")
con.execute("insert into test.test values(1, 'foo');")

con = db.connect()
assert con.execute("select * from test.test").fetchall() ==  [(1L, 'foo')]

con = db.connect()
con.execute("truncate table test.test")

con = db.connect()
assert con.execute("select * from test.test").fetchall() == []  ### Fails
```

See:
http://docs.sqlalchemy.org/en/latest/core/connections.html#understanding-autocommit

Fix:
Overwrite https://github.com/zzzeek/sqlalchemy/blob/b9d0e2d5c55f68193fae001bb553a51018ab8ed6/lib/sqlalchemy/engine/default.py#L780 in dialect.

**Comment by BY-jk** [comment]
quickly looking at it, the fix should redefine the referred regexp
https://github.com/zzzeek/sqlalchemy/blob/b9d0e2d5c55f68193fae001bb553a51018ab8ed6/lib/sqlalchemy/engine/default.py#L26

From what I see, `MERGE` and `TRUNCATE` should be added to the list.

**Comment by exaSR** [comment]
Maybe you should ask the other way round:
Is there any statement on Exasol that should/can *not* be autocommitted?

**Comment by hoffmann** [comment]
@BY-jk I'm not sure If upstream is willing to include statements in sqlachemy that are specific to certain dialects and not supported by all.

**Comment by hoffmann** [comment]
@exaSR I don't want to change the standard commit behaviour for eg SELECT statements, because a commit might trigger INDEX builds/updates. So I'd like to have a list of all data changing statements.

**Comment by exaSR** [comment]
@hoffmann Actually, the SELECT might trigger an index build, while the commit would publish that index such that it does not get built repeatedly by other transactions...
In Exasol, basically any statement could be data-changing when you classify table statistics and indices as data.

But I agree, never change a running system unless there are problems.

**Comment by BY-jk** [comment]
@hoffmann not an upstream change. I assume the regex can be overwritten in the EXASOL specific dialect. If this is not possible the method needs to be overwritten.
